/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NonEmptyString = string;
export type UniqueStrings = NonEmptyString[];
export type WorkMode = "on-site" | "hybrid" | "remote";
export type EmploymentType =
  | "full-time"
  | "part-time"
  | "self-employed"
  | "freelance"
  | "contract"
  | "internship"
  | "apprenticeship"
  | "seasonal";
export type ApproximateDate = string | string;
export type Experiences = Experience[];
export type Recommendations = Recommendation[];

/**
 * The professional experiences and skills of an individual
 */
export interface Resume {
  $schema: NonEmptyString;
  contact?: Contact;
  profile?: Profile;
  objective?: Objective;
  experiences?: Experiences;
  recommendations?: Recommendations;
}
export interface Contact {
  fullName?: NonEmptyString;
  casualName?: NonEmptyString;
  pronouns?: NonEmptyString;
  location?: NonEmptyString;
  emailAddress?: string;
  phoneNumber?: string;
}
export interface Profile {
  headline?: NonEmptyString;
  about?: NonEmptyString;
  skills?: Skill[];
  languages?: UniqueStrings;
  resources?: Resource[];
}
export interface Skill {
  name: NonEmptyString;
  competencies?: UniqueStrings;
}
export interface Resource {
  title?: string;
  uri: string;
}
export interface Objective {
  /**
   * The date when first available for hire. A date in the past or no date is considered to mean immediately.
   */
  startDate?: string;
  /**
   * Taking extended time to find the best fit.
   */
  isCasual?: boolean;
  roles?: UniqueStrings;
  workModes?: WorkMode[];
  employmentTypes?: EmploymentType[];
}
export interface Experience {
  companyName?: NonEmptyString;
  title?: NonEmptyString;
  employmentType?: EmploymentType;
  location?: NonEmptyString;
  workMode?: WorkMode;
  startDate?: ApproximateDate;
  endDate?: ApproximateDate;
  summary?: NonEmptyString;
  highlights?: UniqueStrings;
}
export interface Recommendation {
  author?: Contact;
  relationship?: NonEmptyString;
  message?: NonEmptyString;
}
