name: Run Tests

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run lint
