name: Test

on:
  workflow_call:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: "npm"
      - run: npm ci
      - run: npm run test-coverage
      - run: npm run lint
      - run: npm run check-format
      - run: npm run check-types
